# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: aplicativo_db
      MYSQL_USER: igor
      MYSQL_PASSWORD: Mudar@1234
    ports:
      - 3306:3306
  mongo_container:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: igor
      MONGO_INITDB_ROOT_PASSWORD: senha123
    ports:
      - 27017:27017